server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: javalabs
  data:
    rest:
      detection-strategy: all
      base-path: /api
  datasource:
    url: jdbc:h2:mem:accounting
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
