server:
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: javalabs
  datasource:
    url: jdbc:h2:mem:accounting;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
  mvc:
    problemdetails:
      enabled: true
  threads:
    virtual:
      enabled: true
